### ISSUE TITLE
Maven repo https://www.matthewo.tech/maven/ is offline

### ISSUE THREAD

**Issue by acompton** [MatthewOates36/fast-load-plugin#2]
We'd like to try out fast-load, but it looks like the Maven repo https://www.matthewo.tech/maven/ in the [Installation instructions](https://gist.github.com/MatthewOates36/1e38452236dc9f145c3a6b2addfb418f) is currently offline. Are you still supporting this library?

**Comment by MatthewOates36** [comment]
fast-load is still supported. As far as I'm aware the Maven repo is up and running. Would you please confirm that [this](https://www.matthewo.tech/maven/org/team11260/fast-load-plugin/0.1.2/fast-load-plugin-0.1.2.module) works on your development computer.

**Comment by acompton** [comment]
This turned out to be a network configuration issue on my end that was blocking dependency resolution. Apologize for the confusion! Thanks for your efforts supporting this library for the FIRST community.
